name: Build and Deploy GitHub Pages (Storybook)

on:
  push:
    branches:
      - master # Set a branch name to trigger deployment

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Cache pnpm
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-

      - name: Cache Build output (woxox-ui)
        uses: actions/cache@v2
        with:
          path: '**/woxox-ui/dist'
          key: ${{ runner.os }}-woxox-ui-${{ hashFiles('**/woxox-ui/dist') }}
          restore-keys: ${{ runner.os }}-woxox-ui-

      - name: Cache Build output (woxox-icon)
        uses: actions/cache@v2
        with:
          path: '**/woxox-icon/dist'
          key: ${{ runner.os }}-woxox-icon-${{ hashFiles('**/woxox-icon/dist') }}
          restore-keys: ${{ runner.os }}-woxox-icon-

      - name: Cache Build output (storybook)
        uses: actions/cache@v2
        with:
          path: '**/storybook-static'
          key: ${{ runner.os }}-storybook-static-${{ hashFiles('**/storybook-static') }}
          restore-keys: ${{ runner.os }}-storybook-static-

      - name: Install Dependencies
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install -g pnpm
      - run: pnpm install

      - name: Build Storybook
        run: pnpm build-storybook

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        # If you're changing the branch from main,
        # also change the `main` in `refs/heads/main`
        # below accordingly.
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./apps/storybook/storybook-static
